language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3"

install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt
    - pip install nose
    - python setup.py install

script: nosetests -s

